### ISSUE TITLE
Hugo Papermod: after hiding authors, the dot separator remains

### ISSUE THREAD

**Issue by tiadaguru** [hyvor/hyvor-blogs-themes#7]
If one hides author names on the published site via the config.yaml (`true` → `false`) in the Hugo Papermod theme, the theme does not remove the · dot separator after the date. 

## Steps to reproduce:

1. In the Hugo Papermod theme, open config.yaml in the theme and set authors under loop and post to `false`.

2. Open the published site. The authors are successfully removed, however the · dot separator remains.

## Suggested fix:

1. After disabling authors, the dot separator should also be removed. That would look a little cleaner.

## config.yaml with hidden authors
<img width="542" alt="Xnapper-2023-04-04-11 11 21" src="https://user-images.githubusercontent.com/56522083/229838938-68aaf4d4-87d8-4227-94cc-e4bd551fec15.png">

## home page (loop) with extra · dot separator
<img width="841" alt="Xnapper-2023-04-04-11 10 13" src="https://user-images.githubusercontent.com/56522083/229839041-0d138722-aa1c-4c2c-84a8-d260c3c5717b.png">

## post with extra · dot separator
<img width="794" alt="Xnapper-2023-04-04-11 10 42" src="https://user-images.githubusercontent.com/56522083/229839060-9cab9cad-2f55-46ae-8346-f3deb18b4947.png">

**Comment by supun-io** [comment]
Thanks for creating the issue. Fixed in https://github.com/hyvor/hyvor-blogs-themes/commit/ff13f5307c880f5ae9a638d48939494fd9430102
