### ISSUE TITLE
Hugo Papermod: dates do not match on the post (date A) vs loop (date B)

### ISSUE THREAD

**Issue by tiadaguru** [hyvor/hyvor-blogs-themes#8]
## Links
Home page (showing **March 13, 2023**): https://cahaya.hyvorblogs.io/
Post itself (showing **April 4, 2023**): https://cahaya.hyvorblogs.io/emancipatory-education-via-a-curriculum-rewrite

## Screenshot
<img width="1440" alt="Xnapper-2023-04-04-11 28 48" src="https://user-images.githubusercontent.com/56522083/229842519-75afaf96-e934-4dca-846f-043b799f213f.png">

**Comment by supun-io** [comment]
Fixed https://github.com/hyvor/hyvor-blogs-themes/commit/1a93289c025b7a807953089cb17931037c07340d
